version: "3.9"

services:
    backend:
        image: ulticlipper-backend-dev
        build:
            dockerfile: deploy/dockerfiles/Dockerfile-dev-django
        container_name: ulticlipper-backend-dev
        ports:
            - "80:80"
        volumes:
            - .:/app:z
        restart: always
    frontend:
        image: ulticlipper-frontend-dev
        build:
            dockerfile: deploy/dockerfiles/node-watch.dockerfile
        volumes:
            - ./javascript:/app/javascript:z
            - ./styles:/app/styles:z
            - ./static:/app/static
        restart: always
