version: "3.9"

services:
    proxy:
        depends_on:
        - backend
        image: caddy:2.6.1
        container_name: ulticlipper-proxy-dev
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./static:/static
            - ./deploy/dev.Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
    backend:
        build:
            dockerfile: deploy/dockerfiles/django-dev.dockerfile
        container_name: ulticlipper-backend-dev
        environment:
            ENV_NAME: dev
        volumes:
            - .:/app:z
        restart: always
    database:
        image: postgres:14.5
        container_name: ulticlipper-database-dev
        environment:
          POSTGRES_USER: backend
          POSTGRES_PASSWORD: good_password
        restart: always
    frontend:
        build:
            dockerfile: deploy/dockerfiles/node-watch.dockerfile
        volumes:
            - ./javascript:/app/javascript:z
            - ./styles:/app/styles:z
            - ./static:/app/static
        restart: always

volumes:
    caddy_data:
        external: false
