FROM python:3.10.7

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt


# CMD sleep 10; python manage.py runserver 0.0.0.0:8000
CMD python manage.py runserver 0.0.0.0:8000
