# Generated by Django 4.1.1 on 2022-09-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField()),
                ('vid_id', models.CharField(max_length=11)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
    ]
