# Generated by Django 4.1.1 on 2023-01-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_clip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggroup',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.taggroup'),
        ),
    ]
