# Generated by Django 4.1.1 on 2023-01-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_taggroup_tags_tag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='backend.taggroup'),
        ),
    ]
