# Generated by Django 4.1.1 on 2023-03-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_clip_team_comment_team_tag_team_taggroup_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taggroup',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
