# Generated by Django 4.1.1 on 2023-03-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_comment_timestamp'),
        ('backend', '0014_clip_type'),
    ]

    operations = [
    ]
