FROM python:3.10.7

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt

CMD python manage.py makemigrations \
    && python manage.py migrate \
    && python manage.py loaddata backend/fixtures/seed-events.json \
    && python manage.py collectstatic --no-input \
    && python manage.py createsuperuser --username admin --email none@none.com --no-input
